### ISSUE TITLE
Can I add sidelines at or near particular lines in my file?

### ISSUE THREAD

**Issue by CarlQLange** [emacs-sideline/sideline#12]
I would like to constantly display my sidelines on several lines in my buffer, not just on the current cursor location. Is there a way to do this? 

In any case, thanks a lot for this package, really helpful!

**Comment by CarlQLange** [comment]
Yes, I guess I am looking for sidelines to be always visible in the whole buffer regardless of cursor position.

You can see an example of what I'm thinking of in this screenshot from VSCode:

![image](https://user-images.githubusercontent.com/859820/232083429-4d1ba5b1-0932-43c5-8d46-b9f34d322859.png)

The "You, 2 months ago" sections are visible even though my cursor is on line 16.

I think this could be accomplished by modifying [`sideline--find-line`](https://github.com/emacs-sideline/sideline/blob/master/sideline.el#L311) to take an optional `line-number` argument, and extending it to find a space near that `line-number` if it's given. What do you think?

**Comment by jcs090218** [comment]
This looks like it has to be made with other plugin, like https://github.com/jcs-elpa/codemetrics. Here is another example, see https://github.com/jcs-elpa/codemetrics/issues/1#issuecomment-1496943831. I don't think using the sideline is a good idea since the feel and look will be different. 🤔

**Comment by CarlQLange** [comment]
Ah, thanks so much for the pointer to that library, that's exactly the UX I was looking for! Appreciate it, and nice job on Two great packages!
