### ISSUE TITLE
Empty continuation lines are shown when the buffer is enough narrow (in terminal)

### ISSUE THREAD

**Issue by aciceri** [emacs-sideline/sideline#13]
Hey, great package!

I'm using it with `sideline-flymake` (opening the issue here since I'm 99% this has not to do with `sideline-flymake`) in order to show errors but when the buffer is sufficiently narrow (half screen is enough, no need to make it ridiculously narrow) also the sideline's continuation line is shown. Random example:

![image](https://github.com/emacs-sideline/sideline/assets/2318843/752fa1bd-4c68-4c4d-8e34-dc60dd6259d0)

The funny thing is that the continuation is even empty!

A similar thing happen when I try 

![image](https://github.com/emacs-sideline/sideline/assets/2318843/4a77fdfb-f7d4-4702-9e27-6bd1e9ecd78d)

Important detail: **I'm on terminal** and I haven't tried with graphical Emacs (I compiled it without graphic support).

For now my solution was overriding `sideline--create-ov` adding a further little offset, this way I always have a useless padding on the right but it's always better than all of these annoying continuations lines.

![image](https://github.com/emacs-sideline/sideline/assets/2318843/9563933d-08e2-41d8-aac6-9a57b7992763)

I've tried understanding how the `sideline--create-ov` function works but it's a bit too much for me, especially at this hour.

**Comment by aciceri** [comment]
Don't take too much into account what I just wrote, it's not completely clear to me both how the the offset is calculated why this doesn't work. I just found out that after splitting my frame into two equals windows (`split-window-right`) I encounter this problem only in the left window:

![image](https://github.com/emacs-sideline/sideline/assets/2318843/e180d47b-00b9-4c86-9bdd-1d5043529188)
![image](https://github.com/emacs-sideline/sideline/assets/2318843/019927b6-4b27-4be2-985f-21d691550acf)

So, it's not even true that the continuation line is empty.

**Comment by jcs090218** [comment]
> Important detail: **I'm on terminal and** I haven't tried with graphical Emacs (I compiled it without graphic support).

This is the relevant code between **terminal** and **graphical**.

https://github.com/emacs-sideline/sideline/blob/be5d9386ac3cf840d8c61394563e2293f2014131/sideline.el#L276-L279

But I don't think that's relevant to the issue. 🤔 

> For now my solution was overriding sideline--create-ov adding a further little offset, this way I always have a useless padding on the right but it's always better than all of these annoying continuations lines.

Can you try edit `sideline-format-right`? Maybe add a space on the right; from `"   %s"` to `"   %s "`. 🤔

**Comment by aciceri** [comment]
It was the first thing I tried and I believe that in the screenshots I sent in my first message I forgot it set to `"   %s "`.

With `"   %s "`:

![image](https://github.com/emacs-sideline/sideline/assets/2318843/302a6dd2-6db9-4a60-a3db-5a61319ab25d)
![image](https://github.com/emacs-sideline/sideline/assets/2318843/43a21af8-2b75-4d29-9409-6a56848f6fff)

With `"   %s"`:
![image](https://github.com/emacs-sideline/sideline/assets/2318843/78f8d890-994f-488b-a311-fa6b1987b253)
![image](https://github.com/emacs-sideline/sideline/assets/2318843/0d2b1a83-f54f-4d53-a28c-f236a1efa32f)

**Comment by aciceri** [comment]
```elisp
(defun my-sideline--align (&rest lengths)
    "Align sideline string by LENGTHS from the right of the window."
    (list (* (window-font-width)
	    (+ (apply #'+ lengths) (if (display-graphic-p) 1 3)))))

(advice-add 'sideline--align :override #'my-sideline--align)
```

Doing so seems to work even if it's not an optimal solution because the last column is not used sometimes.
Said this, today I'll try it at work, if I don't face this problem anymore I can open a PR (if you want).

**Comment by jcs090218** [comment]
> It was the first thing I tried and I believe that in the screenshots I sent in my first message I forgot it set to "   %s ".

Thanks for testing it out! 🚀 Apparently, it does not work! 😓 

> Doing so seems to work even if it's not an optimal solution because the last column is not used sometimes.

Yeah, I would like to seek the ideal solution. We should figure out the reason why a new line (length too long) has been added.

I've tried it on my machine, and I cannot reproduce this. 🤔 Can you try turning on and off a few minor modes and see what could be the culprit? Or try `emacs -q` and try to enable one package at a time.

**Comment by aciceri** [comment]
Minimal steps to reproduce I found:
1. run `emacs -q`
2. open the scratch buffer
3. paste the following
```elisp
(require 'sideline)
(require 'sideline-flymake)
(setq sideline-flymake-display-mode 'line)
(setq sideline-backends-right '(sideline-flymake))

(sideline-mode +1)
(flymake-mode +1)
```
4. `M-x eval-buffer`
5. Split the frame with `C-x 3`
6. Write something that causes an error/warning and move the cursor over

![image](https://github.com/emacs-sideline/sideline/assets/2318843/07a7b4d8-2e68-4036-b9af-682fb14945f4)
![image](https://github.com/emacs-sideline/sideline/assets/2318843/531df6ca-38d9-4d45-93b0-9d5e0a9df64c)

**Comment by jcs090218** [comment]
Hmm... still can't reproduce it. (on 29.1 as well)

![2023-08-08 14 49 10](https://github.com/emacs-sideline/sideline/assets/8685505/2a84b065-92b3-4a9c-9d92-7949f35d2ff3)

My next guess is something wrong with the GUI library we are using. 🤔

**Comment by aciceri** [comment]
Ahah don't worry. PR opened :)
