### ISSUE TITLE
Right-aligning via sideline--align: remove 'subtract 1' call to avoid bleeding 1 character into the next line  

### ISSUE THREAD

**Issue by DivineDominion** [emacs-sideline/sideline#18]
I found that I needed to remove the `(1- ...)` when right-aligning the sideline overlay.

The code is this:
https://github.com/emacs-sideline/sideline/blob/20e04fa2fd4dcc0cba47d0336aab37f3f42909d3/sideline.el#L438

The "fix" would be:

               (propertize " " 'display `((space :align-to (- right ,(sideline--align len-title offset)))

I don't quite understand why that's the case, though.

(Am using GUI Emacs for macOS)

I'm not good at debugging Elisp -- I can fiddle with stuff, run it again, and see if it helps, like I did here, but I'm not sure how to figure out the actual culprit. Hints welcome!

### With `(1- ...)` but without truncating lines (my default)

![2024-01-06 10-42-04 Emacs - Logger php](https://github.com/emacs-sideline/sideline/assets/59080/10b5b7a1-ef6f-4049-9297-09096c4e57ea)

### With `(1- ...)` and truncating lines

![2024-01-06 10-41-20 Emacs - Logger php](https://github.com/emacs-sideline/sideline/assets/59080/617e8207-c32e-48ed-9aeb-9d8d94431cc3)

That's bearable, but I found that replacing `(1- len-title)` with just `len-title` fixes things:

### Without `(1- ...)`

![2024-01-06 10-41-05 Emacs - Logger php](https://github.com/emacs-sideline/sideline/assets/59080/2bbed22e-d58c-4cca-acc2-cce0ba87e7d6)

**Comment by DivineDominion** [comment]
Ah, since `sideline--align` is a function, it'd be possible to tweak the offset there, too, and use a length offset of `2` instead of `1`:

```elisp
(defun sideline--align (&rest lengths)
  "Align sideline string by LENGTHS from the right of the window."
  (list (* (window-font-width)
           (+ (apply #'+ lengths) (if (display-graphic-p) 2 3)))))
```

That's easier to override in my config. Ideas how to figure out the root problem still welcome, though :)

**Comment by jcs090218** [comment]
Can you try with `emacs -q`? Generally, `sideline` can be miscalculated depending on the packages you use. Can you try turning some minor modes on/off? Let me know if you find anything. I would like to include a fix in this package. :)

**Comment by antoineB** [comment]
I have the same problem.
1. Don't occur if run with -nw.
2. If I have fringe activated (setq overflow-newline-into-fringe t) resolve the problem.

**Comment by jcs090218** [comment]
Would this be a macOS-specific problem? 🤔 Sorry, I'm still a bit confuse.

**Comment by antoineB** [comment]
I am running pgtk emacs on linux and I use Source Code Pro font. If I use another font (DejaVu Sans for instance) the problem disappear.

**Comment by jcs090218** [comment]
I think the issue is due to the font calculation? 🤔 

https://github.com/emacs-sideline/sideline/blob/3bd6315e8c3437b262d6f9975f37d94ac84d0720/sideline.el#L235-L240

I would need sometime to investigate it.

**Comment by jcs090218** [comment]
I've tried use the Source Code Pro on Windows, but it seems to work. 😕

**Comment by antoineB** [comment]
Here is how it looks:

![Screenshot from 2024-02-28 22-28-57](https://github.com/emacs-sideline/sideline/assets/461772/822acc9b-820e-4e5d-9a65-622af80c9cbe)

I don't think the problem comes from `sideline--str-len`, here is what I get:
```
(length "antoineB, oct. 28 2023 15:49:54 ◉ Add sql-ts-mode.el file to base the mode on another") ;; 85
(sideline--str-len "antoineB, oct. 28 2023 15:49:54 ◉ Add sql-ts-mode.el file to base the mode on another") ;; 85
```

**Comment by antoineB** [comment]
Here is without the fringes.

![Screenshot from 2024-02-28 22-40-44](https://github.com/emacs-sideline/sideline/assets/461772/5a63e7be-96d3-4ea0-9304-448a301e932c)

I have resized to different size but it doesn't change the problem.

**Comment by jcs090218** [comment]
Can you try the latest on master branch? I've done a couple of things.

1. Remove text properties in pixel calculation (some properties will affect the length) https://github.com/emacs-sideline/sideline/blob/1dc13272b6b1ba6fc0c246f4cd150752ae6a5f1d/sideline.el#L236
2. Use the string's pixel size directly https://github.com/emacs-sideline/sideline/blob/1dc13272b6b1ba6fc0c246f4cd150752ae6a5f1d/sideline.el#L283-L288

I hope these changes solve this issue since I don't know what is causing this bug. 🤔

**Comment by antoineB** [comment]
![Screenshot from 2024-02-29 12-11-09](https://github.com/emacs-sideline/sideline/assets/461772/b5ca0ac9-f82a-455f-a098-697eb5ea90b6)
In this picture we can see that the cursor at the end of the line is halfed, `(- (window-width) (window-max-chars-per-line))` gives 1. 

Therefor the sideline-blame shown above is offseted by 1 in `sideline--align`.

Another thing I don't understand the sideline-blame message is not characters aligned with the line below even the 2 lines use the same face.

**Comment by jcs090218** [comment]
> Another thing I don't understand the sideline-blame message is not characters aligned with the line below even the 2 lines use the same face.

My guess is because it's displays from the right? 🤔 

> After resizing the window I can align the characters, the sideline-blame text is displayed next to the right border, but the window-width and window-max-chars-per-line values still off by 1 char.

Hmmm... I guess there are some miscalculations in the window width.

**Comment by antoineB** [comment]
```emacs-lisp
(defun sideline--align (str offset)
  "Align sideline STR from the right of the window.

Argument OFFSET is additional calculation from the left/right alignment."
  (list (+
         ;; If the sideline text is displayed without at least 1 pixel gap from the right fringe and
         ;; overflow-newline-into-fringe is not true, emacs will line wrap it.
         (if (and (display-graphic-p)
                  (> (nth 1 (window-fringes)) 0)
                  (not overflow-newline-into-fringe))
             1
           0)
         (* (window-font-width)
            (+ offset (if (display-graphic-p)
                          ;; If right fringe is deactivated add 1 offset for line wrap char.
                          (if (= 0 (nth 1 (window-fringes))) 1 0)
                        1)))
           (sideline--string-pixel-width str))))
```

The problem was is a char is close with 0 pixel gap to the right fringe and overflow-newline-into-fringe set to nil then emacs line wrap.
For @DivineDominion I see you have no right fringe, if you use emacs in a terminal did you try use sideline.el from master ?
If you use gui emacs without a fringe you try my function.

**Comment by DivineDominion** [comment]
Nice work :)
