### ISSUE TITLE
Error: void-fuction string-pixel-width

### ISSUE THREAD

**Issue by Blade6570** [emacs-sideline/sideline#2]
Hey when I activate sideline-flycheck, it throws the above error and changing the `string-pixel-width` function to `shr-string-pixel-width` solves the issue. 
https://github.com/emacs-sideline/sideline/blob/5b600012bdba1ed5843ae528f73eecca5c0475e3/sideline.el#L182

I am using emacs 28.1 native compilation on WSL2 Ubuntu-21.04.

**Comment by jcs090218** [comment]
Ah... okay. I guess the function `string-pixel-width` only exists in Emacs 29 or above.

**Comment by jcs090218** [comment]
Okay, I think it should be fixed by now! Thanks!
