### ISSUE TITLE
String width calculation

### ISSUE THREAD

**Issue by seagle0128** [emacs-sideline/sideline#23]
`string-pixel-width` is available in 29.x now.

https://github.com/emacs-sideline/sideline/blob/6ffa1b1accdd78d8a118061c851f5d40b228844c/sideline.el#L250-L265

Should consider the face (e.g. :height) while calculating the font width.

https://github.com/emacs-sideline/sideline/blob/6ffa1b1accdd78d8a118061c851f5d40b228844c/sideline.el#L267-L269

**Comment by jcs090218** [comment]
> `string-pixel-width` is available in 29.x now.

We have our own `string-pixel-width` due to this issue https://github.com/emacs-sideline/sideline/pull/21.

> Should consider the face (e.g. :height) while calculating the font width.

Can you elaborate? 🤔

**Comment by seagle0128** [comment]
> We have our own `string-pixel-width` due to this issue #21.
OK. So the `TODO` in comments can be removed. 

> Can you elaborate? 🤔
I checked again, and seems the new solution will impact the performance. I'm closing it for now.
