### ISSUE TITLE
Error messages not displayed at all for long lines

### ISSUE THREAD

**Issue by AndreaOrru** [emacs-sideline/sideline#24]
I encountered an issue with the display of error messages, particularly in C++ where error messages can be quite long. If the first line of an error message exceeds the horizontal character limit of the window, the entire message is not displayed.

Arguably, the error message should be truncated to fit within the window's horizontal character limit but should still be displayed.

**Comment by jcs090218** [comment]
I've added an option to do this. Now you can do:

```elisp
(setq sideline-force-display-if-exceeds t)
```

**Comment by AndreaOrru** [comment]
Thanks! That's useful, but it's not quite what I had in mind.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/5570e74b-39bd-4acd-b006-db17356bb34c">

As you can see, the line wraps around - what I'd prefer is an option to truncate the error string so that it doesn't result in any line wrap.
