### ISSUE TITLE
(doc) : Table of content links dont work

### ISSUE THREAD

**Issue by rileyrg** [emacs-sideline/sideline#30]
click on a link in your table of contents and it doesnt jump to the correct place in the gitpage readme.

**Comment by jcs090218** [comment]
I assumed the bug is from the upstream `markdown-toc`, related to https://github.com/ardumont/markdown-toc/issues/58.

**Comment by jcs090218** [comment]
Fixed in 19d149ae0e4572dc0c283ca247084ecae5b63352.
